# Generated by Django 2.2.6 on 2020-10-08 23:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('wams_asset_id', models.CharField(default='NA', max_length=100)),
                ('qrcode', models.CharField(default='NA', max_length=100)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('badge_number', models.CharField(default='NA', max_length=100)),
                ('owning_department', models.CharField(choices=[('CB', 'Customer Billing Services'), ('DB', 'Distribution'), ('ED', 'Engineering Services - Distribution'), ('FL', 'Fleet'), ('LN', 'Land'), ('NR', 'NRW'), ('PN', 'Production Northern'), ('PS', 'Production Southern'), ('SD', 'SCADA'), ('WQ', 'Water Quality'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('level_1', models.CharField(choices=[('CB', 'Customer Billing Services'), ('DB', 'Distribution'), ('FL', 'Fleet'), ('GA', 'General Admin'), ('PD', 'Production'), ('SD', 'SCADA'), ('WQ', 'Water Quality'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('level_3', models.CharField(choices=[('ND', 'NRW - District Metering Zone'), ('NT', 'NRW - Transmission Network'), ('NW', 'NRW - Water Balancing Area'), ('PH', 'Pump House'), ('RS', 'Reservoir'), ('VD', 'Valve - Distribution Main'), ('VT', 'Valve - Trunk Main'), ('WT', 'Water Treatment Plant'), ('WL', 'WQ Laboratory Services'), ('WO', 'WQ - Online Analyzer'), ('WR', 'WQ - River Monitoring Station'), ('WS', 'WQ Sampling Station'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('level_4', models.CharField(default='NA', max_length=100)),
                ('level_5', models.CharField(choices=[('AS', 'Aeration System'), ('BR', 'Balancing Reservoir'), ('BD', 'Buildings'), ('CD', 'Chemical Dosing'), ('CS', 'Coagulation System'), ('DT', 'Draw of Tower'), ('ES', 'Earthing System'), ('EP', 'Electrical Panel'), ('ES', 'Electrical System'), ('FS', 'Filtration Process'), ('FC', 'Flocculation'), ('OR', 'Off River Storage Reservoir'), ('RW', 'Raw Water Process'), ('SP', 'Sedimentation Process'), ('SS', 'Solar System'), ('ST', 'Sludge Treament Process'), ('SW', 'Settled Water Process'), ('TI', 'Tangki Imbang 3MG'), ('TO', 'Tangki Imbangan 4MG (OLD)'), ('TN', 'Tangki Imbangan 4MG (NEW)'), ('TS', 'Telemetry System'), ('TP', 'Treatment Process'), ('TW', 'Treated Water Process'), ('WA', 'Water Analysis'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('level_6', models.CharField(choices=[('AP', 'Actiflo Process'), ('AC', 'Activated Carbon Process'), ('AS', 'Aeration System'), ('ES', 'Alum Process'), ('BP', 'Backwash Process'), ('BR', 'Balancing Reservoir'), ('BO', 'Boat House'), ('BU', 'Buildings'), ('CD', 'Chemical Dosing'), ('CM', 'Chemical Process'), ('CP', 'Chlorination Process'), ('CO', 'Coagulation Process'), ('CR', 'Chemical Room'), ('CC', 'Control Centre'), ('CR', 'Control Room'), ('DP', 'Data Process'), ('DS', 'Distrafication'), ('DO', 'Draw Off Process'), ('ES', 'Earthing System'), ('EL', 'Electrical System'), ('FS', 'Facilities System'), ('FP', 'Filtration Process'), ('FW', 'Filtered Water Sampling'), ('FO', 'Flocculation Process'), ('FL', 'Fluoride Process'), ('LB', 'Laboratory'), ('LP', 'Lime Process'), ('OA', 'Online Analyzer'), ('PR', 'Polymer (Residual) Dosing'), ('PA', 'Poly Aluminium Chloride Process'), ('PP', 'Polymer Process'), ('PS', 'Power Supply'), ('RM', 'Rapid Mixing'), ('RE', 'Residual Emergency Lagoon'), ('RT', 'Residual Thickened Pumping Station'), ('RI', 'Raw Water Intake System'), ('RS', 'Raw Water Pumping System'), ('RP', 'Raw Water Process'), ('RE', 'Raw Water Pipeline'), ('RV', 'Reservoir'), ('SS', 'SCADA System'), ('SD', 'Sedimentation Process'), ('SL', 'Settled Water Process'), ('SS', 'Settled Water Sampling'), ('SW', 'Settled Water Pumping System'), ('SB', 'Sludge Balancing'), ('ST', 'Sludge Treament Process'), ('SQ', 'Solid Liquid Separation'), ('SA', 'Solar System'), ('SI', 'Sodium Alumino Silicate Process'), ('SO', 'Soda Ash Process'), ('TA', 'Tangki Sedit SYABAS'), ('TE', 'Telemetry System'), ('TP', 'Treated Water Process'), ('TS', 'Treated Water Sampling'), ('TL', 'Treated Water Pipeline'), ('TW', 'Treated Water Pumping System'), ('TT', 'Treatment Process'), ('WA', 'Water Analysis'), ('WO', 'Workshop'), ('WT', 'Water Transfer'), ('WP', 'Wash Water Process'), ('WR', 'Wash Water Recovery'), ('WS', 'Wash Water System'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('asset_description', models.CharField(default='NA', max_length=100)),
                ('acquired_by', models.CharField(choices=[('AH', 'Asset Handover'), ('PC', 'Procured')], default='AH', max_length=2)),
                ('brand', models.CharField(default='NA', max_length=100)),
                ('model_no', models.CharField(default='NA', max_length=100)),
                ('size_capacity_1', models.FloatField(default=0)),
                ('size_capacity_1_measurement', models.FloatField(default=0)),
                ('size_capacity_2', models.FloatField(default=0)),
                ('size_capacity_2_measurement', models.FloatField(default=0)),
                ('size_capacity_3', models.FloatField(default=0)),
                ('size_capacity_3_measurement', models.FloatField(default=0)),
                ('parent_plate_number', models.CharField(default='NA', max_length=100)),
                ('plate_number', models.CharField(default='NA', max_length=100)),
                ('serial_number', models.CharField(default='NA', max_length=100)),
                ('vendor_part_no', models.CharField(default='NA', max_length=100)),
                ('scada_id', models.CharField(default='NA', max_length=100)),
                ('external_id', models.CharField(default='NA', max_length=100)),
                ('tag_number', models.CharField(default='NA', max_length=100)),
                ('pallet_number', models.CharField(default='NA', max_length=100)),
                ('installed_at', models.DateTimeField(null=True)),
                ('rating', models.CharField(choices=[('1', '1 - Very Good'), ('2', '2 - Good'), ('3', '3 - Average'), ('4', '4 - Popover'), ('5', '5 - Replace')], default='3', max_length=1)),
                ('status', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('maintenance_specification', models.CharField(default='NA', max_length=100)),
                ('bill_of_material', models.CharField(default='NA', max_length=100)),
                ('measuring_type', models.CharField(choices=[('FM', 'Flow Meter Readings'), ('TP', 'Temperature'), ('OT', 'Other')], default='OT', max_length=2)),
                ('is_warranty', models.BooleanField(default=False)),
                ('warranty_period_actual', models.IntegerField(default=0)),
                ('po_cost', models.IntegerField(default=1)),
                ('approval_status', models.CharField(choices=[('AP', 'Approve'), ('RE', 'Reject'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('approval_at', models.DateTimeField(blank=True, null=True)),
                ('reject_remark', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('category', models.CharField(choices=[('AI', 'Asset Identity'), ('PG', 'Primary Category'), ('S1', 'Sub Category 1'), ('S2', 'Sub Category 2')], default='AI', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('category', models.CharField(choices=[('AC', 'Asset / Component'), ('AG', 'Asset Category'), ('AT', 'Asset Type (Asset Primary Category)')], default='AI', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rfid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('rfid_id', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
