# Generated by Django 2.2.6 on 2020-07-05 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('purchased_at', models.DateTimeField(null=True)),
                ('owned_department', models.CharField(choices=[('CB', 'Customer Billing Services'), ('DB', 'Distribution'), ('ED', 'Engineering Services - Distribution'), ('FL', 'Fleet'), ('LN', 'Land'), ('NR', 'NRW'), ('PN', 'Production Northern'), ('PS', 'Production Southern'), ('SD', 'SCADA'), ('WQ', 'Water Quality'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('hierarchy_level_1', models.CharField(choices=[('CB', 'Customer Billing Services'), ('DB', 'Distribution'), ('FL', 'Fleet'), ('GA', 'General Admin'), ('PD', 'Production'), ('SD', 'SCADA'), ('WQ', 'Water Quality'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('hierarchy_level_3', models.CharField(choices=[('ND', 'NRW - District Metering Zone'), ('NT', 'NRW - Transmission Network'), ('NW', 'NRW - Water Balancing Area'), ('PH', 'Pump House'), ('RS', 'Reservoir'), ('VD', 'Valve - Distribution Main'), ('VT', 'Valve - Trunk Main'), ('WT', 'Water Treatment Plant'), ('WL', 'WQ Laboratory Services'), ('WO', 'WQ - Online Analyzer'), ('WR', 'WQ - River Monitoring Station'), ('WS', 'WQ Sampling Station'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('hierarchy_level_4', models.CharField(choices=[('NR', 'NRW'), ('PH', 'Pump House'), ('RS', 'Reservoir'), ('TP', 'Treatment Plant Name'), ('NA', ' Not Available')], default='NA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hierarchy_level_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_hierarchy_level_2', to='locations.Region')),
            ],
        ),
    ]
