# Generated by Django 2.2.6 on 2020-10-08 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='approval_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_approval_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category': 'AG'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_category', to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='identity',
            field=models.ForeignKey(limit_choices_to={'category': 'AI'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_identity', to='assets.AssetGroup'),
        ),
        migrations.AddField(
            model_name='asset',
            name='level_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_level_2', to='locations.Region'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_po_vendor', to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_category',
            field=models.ForeignKey(limit_choices_to={'category': 'AT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_primary_category', to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='rfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_rfid', to='assets.Rfid'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sub_category_1',
            field=models.ForeignKey(limit_choices_to={'category': 'S1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_sub_category_1', to='assets.AssetGroup'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sub_category_2',
            field=models.ForeignKey(limit_choices_to={'category': 'S2'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_sub_category_2', to='assets.AssetGroup'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type_asset',
            field=models.ForeignKey(limit_choices_to={'category': 'AC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_type', to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_warranty_vendor', to='organisations.Organisation'),
        ),
    ]
