# Generated by Django 2.2.6 on 2020-07-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200705_1124'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bill_of_material',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('EL', 'Electrical'), ('MC', 'Mechanical'), ('IS', 'Insturement'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='category_extra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='external_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='grouping_sub_category_1',
            field=models.CharField(choices=[('AR', 'Air Receiver Tank'), ('DL', 'Delivery'), ('HR', 'Horizontal'), ('MP', 'Main Power Suppply'), ('MN', 'Manual'), ('OF', 'Oil Filled'), ('ST', 'Suction'), ('VT', 'Vertical'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='grouping_sub_category_2',
            field=models.CharField(choices=[('CS', 'Casing'), ('DL', 'Delivery'), ('DF', 'Double Flange Swing'), ('EL', 'Electrical Installation'), ('ES', 'End Suction'), ('MS', 'Multi Stage'), ('RP', 'Reduced Port'), ('SP', 'Split'), ('SC', 'Squirrel Cage'), ('ST', 'Suction'), ('VT', 'Vertical'), ('WT', 'Wafer Twin Door'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='hierarchy_level_5',
            field=models.CharField(choices=[('AS', 'Aeration System'), ('BR', 'Balancing Reservoir'), ('BD', 'Buildings'), ('CD', 'Chemical Dosing'), ('CS', 'Coagulation System'), ('DT', 'Draw of Tower'), ('ES', 'Earthing System'), ('EP', 'Electrical Panel'), ('ES', 'Electrical System'), ('FS', 'Filtration Process'), ('FC', 'Flocculation'), ('OR', 'Off River Storage Reservoir'), ('RW', 'Raw Water Process'), ('SP', 'Sedimentation Process'), ('SS', 'Solar System'), ('ST', 'Sludge Treament Process'), ('SW', 'Settled Water Process'), ('TI', 'Tangki Imbang 3MG'), ('TO', 'Tangki Imbangan 4MG (OLD)'), ('TN', 'Tangki Imbangan 4MG (NEW)'), ('TS', 'Telemetry System'), ('TP', 'Treatment Process'), ('TW', 'Treated Water Process'), ('WA', 'Water Analysis'), ('NA', ' Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='hierarchy_level_6',
            field=models.CharField(choices=[('AP', 'Actiflo Process'), ('AC', 'Activated Carbon Process'), ('AS', 'Aeration System'), ('ES', 'Alum Process'), ('BP', 'Backwash Process'), ('BR', 'Balancing Reservoir'), ('BO', 'Boat House'), ('BU', 'Buildings'), ('CD', 'Chemical Dosing'), ('CM', 'Chemical Process'), ('CP', 'Chlorination Process'), ('CO', 'Coagulation Process'), ('CR', 'Chemical Room'), ('CC', 'Control Centre'), ('CR', 'Control Room'), ('DP', 'Data Process'), ('DS', 'Distrafication'), ('DO', 'Draw Off Process'), ('ES', 'Earthing System'), ('EL', 'Electrical System'), ('FS', 'Facilities System'), ('FP', 'Filtration Process'), ('FW', 'Filtered Water Sampling'), ('FO', 'Flocculation Process'), ('FL', 'Fluoride Process'), ('LB', 'Laboratory'), ('LP', 'Lime Process'), ('OA', 'Online Analyzer'), ('PR', 'Polymer (Residual) Dosing'), ('PA', 'Poly Aluminium Chloride Process'), ('PP', 'Polymer Process'), ('PS', 'Power Supply'), ('RM', 'Rapid Mixing'), ('RE', 'Residual Emergency Lagoon'), ('RT', 'Residual Thickened Pumping Station'), ('RI', 'Raw Water Intake System'), ('RS', 'Raw Water Pumping System'), ('RP', 'Raw Water Process'), ('RE', 'Raw Water Pipeline'), ('RV', 'Reservoir'), ('SS', 'SCADA System'), ('SD', 'Sedimentation Process'), ('SL', 'Settled Water Process'), ('SS', 'Settled Water Sampling'), ('SW', 'Settled Water Pumping System'), ('SB', 'Sludge Balancing'), ('ST', 'Sludge Treament Process'), ('SQ', 'Solid Liquid Separation'), ('SA', 'Solar System'), ('SI', 'Sodium Alumino Silicate Process'), ('SO', 'Soda Ash Process'), ('TA', 'Tangki Sedit SYABAS'), ('TE', 'Telemetry System'), ('TP', 'Treated Water Process'), ('TS', 'Treated Water Sampling'), ('TL', 'Treated Water Pipeline'), ('TW', 'Treated Water Pumping System'), ('TT', 'Treatment Process'), ('WA', 'Water Analysis'), ('WO', 'Workshop'), ('WT', 'Water Transfer'), ('WP', 'Wash Water Process'), ('WR', 'Wash Water Recovery'), ('WS', 'Wash Water System'), ('NA', ' Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='installed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='internal_detail_indentity',
            field=models.CharField(choices=[('P1', 'Pump-1'), ('P2', 'Pump-2'), ('M1', 'Motor-1'), ('M2', 'Motor-2'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_hand_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_procured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_specification',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='measuring_type',
            field=models.CharField(choices=[('FM', 'Flow Meter Readings'), ('TP', 'Temperature'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_no',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='msize_capcity_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='msize_capcity_1_measurement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='msize_capcity_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='msize_capcity_2_measurement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='msize_capcity_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='msize_capcity_3_measurement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='pallet_number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_plate_number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='plate_number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_po_vendor', to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_category',
            field=models.CharField(choices=[('BV', 'Butterfly Valve'), ('CA', 'Chain Block'), ('CE', 'Check Valve'), ('HT', 'Hydropneumatic Tank'), ('MS', 'Main Switchboard'), ('MT', 'Motor'), ('PG', 'Presuure Gauge'), ('PP', 'Pump'), ('SV', 'Sluice Valve'), ('SA', 'Surge Anticipating Valve'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='rating',
            field=models.CharField(choices=[('1', '1 - Very Good'), ('2', '2 - Good'), ('3', '3 - Average'), ('4', '4 - Popover'), ('5', '5 - Replace')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='scada_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='tag_number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='type_asset',
            field=models.CharField(choices=[('AS', 'Asset'), ('CP', 'Component'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_period_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_warranty_vendor', to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
