# Generated by Django 2.2.6 on 2020-10-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20201008_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sub_category_1',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sub_category_2',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
