# Generated by Django 2.2.6 on 2020-12-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetregistration',
            name='status',
            field=models.CharField(choices=[('RG', 'Registered'), ('AP', 'Approve'), ('RJ', 'Reject')], default='NA', max_length=2),
        ),
    ]
