# Generated by Django 2.2.6 on 2020-12-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20201228_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetregistration',
            old_name='acctually_warranty_period',
            new_name='actual_warranty_period',
        ),
        migrations.AddField(
            model_name='assetregistration',
            name='asset_status',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('IC', 'Incomplete'), ('PR', 'Processed'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='NA', max_length=2),
        ),
    ]
