# Generated by Django 2.2.6 on 2020-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_hand_over',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_procured',
        ),
        migrations.AddField(
            model_name='asset',
            name='acquired_by',
            field=models.CharField(choices=[('AH', 'Asset Handover'), ('PC', 'Procured')], default='AH', max_length=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='rfid_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hierarchy_level_4',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
