# Generated by Django 2.2.6 on 2020-07-14 07:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200714_0702'),
        ('assets', '0004_auto_20200713_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('category', models.CharField(choices=[('AI', 'Asset Identity'), ('PG', 'Primary Category'), ('S1', 'Sub Category 1'), ('S2', 'Sub Category 2')], default='AI', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('category', models.CharField(choices=[('AC', 'Asset / Component'), ('AG', 'Asset Category'), ('AT', 'Asset Type (Asset Primary Category)')], default='AI', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rfid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('rfid_id', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='hierarchy_level_1',
            new_name='level_1',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='hierarchy_level_3',
            new_name='level_3',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='hierarchy_level_4',
            new_name='level_4',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='hierarchy_level_5',
            new_name='level_5',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='hierarchy_level_6',
            new_name='level_6',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='owned_department',
            new_name='owning_department',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category_extra',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='grouping_sub_category_1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='grouping_sub_category_2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='hierarchy_level_2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='internal_detail_indentity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='msize_capcity_1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='msize_capcity_1_measurement',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='msize_capcity_2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='msize_capcity_2_measurement',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='msize_capcity_3',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='msize_capcity_3_measurement',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='rfid_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='level_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_level_2', to='locations.Region'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='size_capacity_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='size_capacity_1_measurement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='size_capacity_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='size_capacity_2_measurement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='size_capacity_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='size_capacity_3_measurement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor_part_no',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='wams_asset_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category': 'AG'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_category', to='assets.AssetType'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='primary_category',
            field=models.ForeignKey(limit_choices_to={'category': 'AT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_primary_category', to='assets.AssetType'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_asset',
            field=models.ForeignKey(limit_choices_to={'category': 'AC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_type', to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='identity',
            field=models.ForeignKey(limit_choices_to={'category': 'AI'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_identity', to='assets.AssetGroup'),
        ),
        migrations.AddField(
            model_name='asset',
            name='rfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_rfid', to='assets.Rfid'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sub_category_1',
            field=models.ForeignKey(limit_choices_to={'category': 'S1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_sub_category_1', to='assets.AssetGroup'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sub_category_2',
            field=models.ForeignKey(limit_choices_to={'category': 'S2'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_sub_category_2', to='assets.AssetGroup'),
        ),
    ]
