# Generated by Django 2.2.6 on 2020-12-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20201229_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetregistration',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('IC', 'Incomplete'), ('NP', 'New Process'), ('PR', 'Processed'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='IC', max_length=2),
        ),
    ]
