# Generated by Django 2.2.6 on 2021-01-06 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20201230_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBadgeFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_uuid', models.CharField(default='NA', max_length=100)),
                ('asset_primary_category', models.CharField(default='NA', max_length=100)),
                ('short', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='NA', max_length=100)),
                ('latest_no', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
