# Generated by Django 2.2.6 on 2021-01-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assetbadgeformat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetregistration',
            old_name='vehicle_roadtarate',
            new_name='vehicle_roadtax_rate',
        ),
    ]
