# Generated by Django 2.2.6 on 2021-01-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210107_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetregistration',
            old_name='asset_critically',
            new_name='asset_criticality',
        ),
        migrations.RenameField(
            model_name='assetregistration',
            old_name='internal_asset_adentity',
            new_name='internal_asset_identity',
        ),
    ]
