# Generated by Django 2.2.6 on 2021-01-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210118_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetAttribute',
        ),
        migrations.DeleteModel(
            name='AssetAttributeColumn',
        ),
    ]
