# Generated by Django 2.2.6 on 2021-01-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20210119_0745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetLocation',
        ),
    ]
