# Generated by Django 2.2.6 on 2021-01-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_assetlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_attributes',
            field=models.ManyToManyField(default='', null=True, to='assets.AssetAttribute'),
        ),
    ]
