# Generated by Django 2.2.6 on 2021-01-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_asset_asset_attributes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetAttributeColumn',
        ),
    ]
