# Generated by Django 2.2.6 on 2021-01-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_assetattributecolumn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetLocation',
        ),
    ]
