# Generated by Django 2.2.6 on 2021-01-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_assetattributecolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_attributes',
            field=models.ManyToManyField(blank=True, null=True, to='assets.AssetAttribute'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='measurement_types',
            field=models.ManyToManyField(blank=True, null=True, to='assets.AssetMeasurementType'),
        ),
    ]
