# Generated by Django 2.2.6 on 2021-01-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_assetattributecolumn'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='assetlocation',
        #     old_name='current_date_of_quit_rent',
        #     new_name='current_rate_of_quit_rent',
        # ),
    ]
