# Generated by Django 2.2.6 on 2021-01-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_auto_20210120_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_attributes',
            field=models.ManyToManyField(blank=True, to='assets.AssetAttribute'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='measurement_types',
            field=models.ManyToManyField(blank=True, to='assets.AssetMeasurementType'),
        ),
    ]
