# Generated by Django 2.2.6 on 2021-01-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_assetlocation'),
        ('assets', '0020_auto_20210120_1641'),
        ('assets', '0019_auto_20210121_0757'),
    ]

    operations = [
    ]
