# Generated by Django 2.2.6 on 2021-01-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_merge_20210121_0953'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='asset',
        #     old_name='attached_to_assist_id',
        #     new_name='attached_to_asset_id',
        # ),
        # migrations.RenameField(
        #     model_name='asset',
        #     old_name='handed_over_assist',
        #     new_name='handed_over_asset',
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='location_id',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
    ]
