# Generated by Django 2.2.6 on 2021-01-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_merge_20210121_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='attached_to_assist_id',
            new_name='attached_to_asset_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='handed_over_assist',
            new_name='handed_over_asset',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='current_rate_of_quit_rent',
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='current_date_of_quit_rent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
