# Generated by Django 2.2.6 on 2021-01-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_auto_20210121_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetlocation',
            old_name='current_date_of_quit_rent',
            new_name='current_rate_of_quit_rent',
        ),
    ]
