# Generated by Django 2.2.6 on 2021-01-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_auto_20210121_0953'),
        ('assets', '0023_auto_20210121_0846'),
    ]

    operations = [
    ]
