# Generated by Django 2.2.6 on 2021-01-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_merge_20210121_1418'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='asset',
        #     old_name='attached_to_assist_id',
        #     new_name='attached_to_asset_id',
        # ),
        # migrations.RenameField(
        #     model_name='asset',
        #     old_name='handed_over_assist',
        #     new_name='handed_over_asset',
        # ),
        migrations.RemoveField(
            model_name='assetattribute',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='asset_critically',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='bo',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='current_rate_of_assessment',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='environment_rating',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='location_disposition',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='maintenance_manager_name',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='parent_lo_or_org',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='plan_pre_computation_num',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='postal',
        ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='location_id',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        migrations.AddField(
            model_name='asset',
            name='owning_access_group_nam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetattribute',
            name='characteristic_type_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Bo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='asset_criticality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='current_rate_Of_assesment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='environmental_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='locatin_disposition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='main_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='maintenance_manager_nam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='parent_loc_or_org',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='parent_location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='plan_pre_computation_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='planner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetmeasurementtype',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetmeasurementtype',
            name='measurement_identifie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_attributes',
            field=models.ManyToManyField(null=True, to='assets.AssetAttribute'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='measurement_types',
            field=models.ManyToManyField(null=True, to='assets.AssetMeasurementType'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owning_access_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty_expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetattribute',
            name='adhoc_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetattribute',
            name='characteristic_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetattribute',
            name='characteristic_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='address_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='assessment_bill_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='assessment_bill_payment_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='backlog_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='breaker',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='connected_to_location_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='cost_center',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='criticality_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='cross_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='current_rate_of_quit_rent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='duty_cycle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='gis_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='land_area_acre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='land_asset_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='land_ownership_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='lease_expired_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='location_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='location_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='main_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='maintenance_manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='owning_org',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='plan_as_built_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='plan_certified_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='planner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='point_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='quit_rent_bill_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='quit_rent_bill_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='rcm_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='run_to_failure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='runtime_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='service_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='service_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='site_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='tag_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='water_asset_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='work_request_approval_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
