# Generated by Django 2.2.6 on 2021-01-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_auto_20210121_1623'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='attached_to_assist_id',
        # ),
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='handed_over_assist',
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='attached_to_asset_id',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='handed_over_asset',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        migrations.AddField(
            model_name='asset',
            name='location_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
