# Generated by Django 2.2.6 on 2021-02-20 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0041_auto_20210218_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAttributeField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type_id', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetLocationSync',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(blank=True, max_length=12)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='attached_to_assist_id',
        # ),
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='handed_over_assist',
        # ),
        migrations.RemoveField(
            model_name='assettype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='name',
        ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='attached_to_asset_id',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='handed_over_asset',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='location_id',
        #     field=models.CharField(blank=True, max_length=12),
        # ),
        # migrations.AddField(
        #     model_name='assetlocation',
        #     name='postal',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        migrations.AddField(
            model_name='assettype',
            name='assessment_class',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assettype',
            name='asset_bussiness_object',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assettype',
            name='asset_type_code',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assettype',
            name='asset_type_description',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assettype',
            name='instance_organisation',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assettype',
            name='owned_organisation',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assettype',
            name='profile_failure',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assettype',
            name='status',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='node_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='connected_to_location_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='asset_id',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='node_id',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
