# Generated by Django 2.2.6 on 2021-04-16 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0043_auto_20210222_1516'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='attached_to_assist_id',
        # ),
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='handed_over_assist',
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='attached_to_asset_id',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='handed_over_asset',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='location_id',
        #     field=models.CharField(blank=True, max_length=12),
        # ),
        # migrations.AddField(
        #     model_name='assetlocation',
        #     name='postal',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        migrations.CreateModel(
            name='AssetMeasurementTypeInbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_type', models.CharField(blank=True, max_length=100)),
                ('action_type', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('measurement_identifie', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('asset_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_measurement_type_inbound_asset_id', to='assets.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAttributeInbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('characteristic_type', models.CharField(blank=True, max_length=100)),
                ('adhoc_value', models.CharField(blank=True, max_length=100)),
                ('characteristic_value', models.CharField(max_length=100, null=True)),
                ('action_type', models.CharField(blank=True, max_length=100)),
                ('characteristic_type_name', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('asset_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_attribute_inbound_asset_id', to='assets.Asset')),
            ],
        ),
    ]
