# Generated by Django 2.2.6 on 2021-05-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0046_auto_20210503_0800'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='attached_to_assist_id',
        # ),
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='handed_over_assist',
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='attached_to_asset_id',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='handed_over_asset',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='location_id',
        #     field=models.CharField(blank=True, max_length=12),
        # ),
        # migrations.AddField(
        #     model_name='assetlocation',
        #     name='postal',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.RemoveField(
        #     model_name='assettype',
        #     name='asset_service_history',
        # ),
        migrations.AddField(
            model_name='assettype',
            name='asset_service_history',
            field=models.ManyToManyField(blank=True, to='assets.AssetServiceHistory'),
        ),
    ]
