# Generated by Django 2.2 on 2021-07-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0052_auto_20210719_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetregistration',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('IC', 'Incomplete'), ('NP', 'New Process'), ('PR', 'Processed'), ('AP', 'Approved'), ('RJ', 'Rejected'), ('TP', 'To Process')], default='IC', max_length=2),
        ),
    ]
