# Generated by Django 2.2 on 2021-07-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0053_auto_20210726_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetregistration',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
