# Generated by Django 2.2 on 2021-08-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0054_auto_20210726_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbadgeformat',
            name='short',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
