# Generated by Django 2.2.6 on 2020-07-14 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0005_auto_20200714_0702'),
        ('medias', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_num', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkActivityTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('teammate', models.ManyToManyField(limit_choices_to={'user_type': 'TC'}, related_name='work_activity_teammate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='completed_by',
        ),
        migrations.AddField(
            model_name='workactivity',
            name='activity_type',
            field=models.CharField(choices=[('CM', 'Corrective Maintenance'), ('CP', 'Compliance'), ('DP', 'Disposal'), ('IT', 'Installation Testing Commisioning'), ('PD', 'Predictive Maintenance'), ('PM', 'Preventive Maintenance'), ('RD', 'Redesign')], default='IT', max_length=2),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_activity_asset', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='status',
            field=models.CharField(choices=[('BL', 'Backlog'), ('IP', 'In Progress'), ('NW', 'New')], default='NW', max_length=2),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='wams_work_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_image', to='medias.Media'),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='flow_rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='pressure_reading',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='running_hours',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_issue_type', to='operations.IssueType'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='workactivityteam',
            name='work_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_activity_team_wa', to='operations.WorkActivity'),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='maintenance_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_activity_maintenance_form', to='operations.Maintenance'),
        ),
    ]
