# Generated by Django 2.2.6 on 2020-10-10 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrequest',
            old_name='bo',
            new_name='bo_status',
        ),
        migrations.AddField(
            model_name='workactivity',
            name='bo_status',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='required_by_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
