# Generated by Django 2.2.6 on 2020-10-08 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequeststatus',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_status_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequeststatus',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_status_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequeststatus',
            name='work_request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_status_work_request_id', to='operations.WorkRequest'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_attachment', to='medias.Media'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequest_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequest_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workclass',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workclass_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workclass',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workclass_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workcategory_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workcategory_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workactivityteam',
            name='teammate',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'TC'}, related_name='work_activity_teammate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workactivityteam',
            name='work_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_activity_team_wa', to='operations.WorkActivity'),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workactivity_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workactivity_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owningorganization',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_owningorganization_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owningorganization',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_owningorganization_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_operationalreading_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_operationalreading_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurementtype',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_measurementtype_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurementtype',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_measurementtype_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bo',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_bo_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bo',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_bo_record_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
