# Generated by Django 2.2.6 on 2020-07-26 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200714_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wams_id', models.CharField(default='NA', max_length=100)),
                ('work_order_description', models.CharField(default='NA', max_length=100)),
                ('planner_cd', models.CharField(default='NA', max_length=100)),
                ('planner_name', models.CharField(default='NA', max_length=100)),
                ('work_order_no', models.CharField(default='NA', max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='name',
        ),
        migrations.AddField(
            model_name='workactivity',
            name='activity_description',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='work_category',
            field=models.CharField(choices=[('CM', 'Corrective Maintenance'), ('CP', 'Compliance'), ('DP', 'Disposal'), ('IT', 'Installation Testing Commisioning'), ('PD', 'Predictive Maintenance'), ('PM', 'Preventive Maintenance'), ('RD', 'Redesign')], default='IT', max_length=2),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='activity_type',
            field=models.CharField(choices=[('PM', 'PREVENTIVE-MAINTENANCE'), ('PI', 'PUMP-INSPECTION'), ('MI', 'MOTOR-INSPECTION'), ('SP', 'STARTER-PANEL-INSPECTION')], default='IT', max_length=2),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='status',
            field=models.CharField(choices=[('BL', 'Backlog'), ('IP', 'In Progress'), ('NW', 'New'), ('CP', 'Completed')], default='NW', max_length=2),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_activity_work_order_no', to='operations.WorkOrder'),
        ),
    ]
