# Generated by Django 2.2.6 on 2020-10-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20201010_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='workactivity',
            name='work_category',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='work_class',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
