# Generated by Django 2.2.6 on 2020-10-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20201010_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='workactivity',
            name='description',
            field=models.TextField(default='NA'),
        ),
    ]
