# Generated by Django 2.2.6 on 2020-10-06 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0003_auto_20200726_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('detail_description', models.TextField(null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_measurementidentifier_modified_by', to=settings.AUTH_USER_MODEL)),
                ('record_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_measurementidentifier_record_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.RenameField(
            model_name='workrequest',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='operationalreading',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='operationalreading',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='operationalreading',
            name='flow_rate',
        ),
        migrations.RemoveField(
            model_name='operationalreading',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='operationalreading',
            name='pressure_reading',
        ),
        migrations.RemoveField(
            model_name='operationalreading',
            name='running_hours',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='activity_description',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='maintenance_form',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='wams_work_id',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='work_category',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='issue_type',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='asset_id',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='badge_number',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_operationalreading_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='reading_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_operationalreading_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='activity_id',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='asset_id',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='completion_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='effective_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='end_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='failure_component',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='failure_mode',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='failure_repair',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='failure_root_cause',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='failure_type',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='measurement_type',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workactivity_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='node_id',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='participation',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='reading_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='reading_type',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workactivity_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='service_history_type',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='start_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='asset_id',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_attachment', to='medias.Media'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_creation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='down_time_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='home_phone',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='last_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='long_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='mobile_phone',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequest_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='node_id',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='planner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_planner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='primary_phone',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequest_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_requestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='required_by_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='work_priority',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='workactivityteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workactivityteam',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkRequestStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='NA', max_length=50)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequeststatus_modified_by', to=settings.AUTH_USER_MODEL)),
                ('record_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequeststatus_record_by', to=settings.AUTH_USER_MODEL)),
                ('work_request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_status_work_request_id', to='operations.WorkRequest')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workclass_modified_by', to=settings.AUTH_USER_MODEL)),
                ('record_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workclass_record_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('detail_description', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workcategory_modified_by', to=settings.AUTH_USER_MODEL)),
                ('record_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workcategory_record_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='OwningOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('detail_description', models.TextField(null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_owningorganization_modified_by', to=settings.AUTH_USER_MODEL)),
                ('record_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_owningorganization_record_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_type_identifier', to='operations.MeasurementIdentifier')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_measurementtype_modified_by', to=settings.AUTH_USER_MODEL)),
                ('record_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_measurementtype_record_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Bo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_bo_modified_by', to=settings.AUTH_USER_MODEL)),
                ('record_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_bo_record_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='measurement_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_reading_measurement_identifier', to='operations.MeasurementIdentifier'),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='measurement_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_reading_measurement_type', to='operations.MeasurementType'),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='owning_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_reading_owning_organization', to='operations.OwningOrganization'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='bo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_bo', to='operations.Bo'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='owning_access_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_owning_access_group', to='operations.OwningOrganization'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='work_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_work_category', to='operations.WorkCategory'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='work_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request_work_class', to='operations.WorkClass'),
        ),
    ]
