# Generated by Django 2.2.6 on 2020-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_workactivity_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workactivity',
            old_name='comments',
            new_name='comments_dt',
        ),
        migrations.RenameField(
            model_name='workactivity',
            old_name='measurement_type',
            new_name='downtime_reason',
        ),
        migrations.RenameField(
            model_name='workactivity',
            old_name='effective_date_time',
            new_name='effective_date_time_dt',
        ),
        migrations.RenameField(
            model_name='workactivity',
            old_name='reading_date_time',
            new_name='effective_date_time_f',
        ),
        migrations.RenameField(
            model_name='workactivity',
            old_name='reading_type',
            new_name='service_history_type_dt',
        ),
        migrations.RenameField(
            model_name='workactivity',
            old_name='service_history_type',
            new_name='service_history_type_f',
        ),
        migrations.RemoveField(
            model_name='workactivity',
            name='current_value',
        ),
        migrations.AddField(
            model_name='workactivity',
            name='comments_f',
            field=models.TextField(default='NA'),
        ),
    ]
