# Generated by Django 2.2.6 on 2020-10-07 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20201007_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalreading',
            name='reading_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 22, 43, 513549)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='completion_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 22, 43, 505841)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='effective_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 22, 43, 506260)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 22, 43, 506331)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='reading_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 22, 43, 506436)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 22, 43, 506296)),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='creation_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 13, 22, 43, 510943)),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='down_time_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 13, 22, 43, 510978)),
        ),
    ]
