# Generated by Django 2.2.6 on 2020-10-07 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20201007_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalreading',
            name='reading_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 45, 41, 412373)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='completion_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 45, 41, 405787)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='effective_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 45, 41, 405998)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 45, 41, 406026)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='reading_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 45, 41, 406073)),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 45, 41, 406013)),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='creation_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 13, 45, 41, 410032)),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='down_time_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 13, 45, 41, 410064)),
        ),
    ]
