# Generated by Django 2.2.6 on 2020-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20201010_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workactivity',
            name='failure_component',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='failure_mode',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='failure_repair',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='failure_root_cause',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='failure_type',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='service_history_type_f',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
    ]
