# Generated by Django 2.2.6 on 2020-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20201007_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalreading',
            name='reading_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='completion_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='effective_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='end_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='reading_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='start_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='creation_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='down_time_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
