# Generated by Django 2.2.6 on 2020-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20201010_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workactivity',
            name='service_history_type_dt',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
    ]
