# Generated by Django 2.2.6 on 2020-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20201010_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='workactivity',
            name='asset_type',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='badge_number',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='detailed_description',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='serial_number',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
