# Generated by Django 2.2.6 on 2020-10-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20201010_1407'),
        ('operations', '0002_auto_20201008_2332'),
    ]

    operations = [
    ]
