# Generated by Django 2.2.6 on 2020-10-13 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_merge_20201011_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='creation_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 13, 3, 59, 3, 579765)),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='first_name',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='home_phone',
            field=models.CharField(blank=True, default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='last_name',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='mobile_phone',
            field=models.CharField(blank=True, default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='primary_phone',
            field=models.CharField(blank=True, default='NA', max_length=20),
        ),
    ]
