# Generated by Django 2.2.6 on 2020-10-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_merge_20201011_0455'),
        ('operations', '0010_merge_20201010_2040'),
    ]

    operations = [
    ]
