# Generated by Django 2.2.6 on 2020-10-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_auto_20201013_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='workactivity',
            name='parent_location',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
