# Generated by Django 2.2.6 on 2020-10-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_merge_20201011_2258'),
        ('operations', '0013_workactivity_parent_location'),
    ]

    operations = [
    ]
