# Generated by Django 2.2.6 on 2020-10-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_workactivity_parent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='workactivity',
            name='answer_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='answer_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='answer_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='comments_pm',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='effective_date_time_pm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workactivity',
            name='service_history_type_pm',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
