# Generated by Django 2.2.6 on 2020-10-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_merge_20201013_0546'),
        ('operations', '0014_auto_20201013_1938'),
    ]

    operations = [
    ]
