# Generated by Django 2.2.6 on 2021-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20210120_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationalreading',
            old_name='measurement_identifier',
            new_name='measurent_identifier',
        ),
        migrations.RenameField(
            model_name='operationalreading',
            old_name='measurement_type',
            new_name='measurent_type',
        ),
        migrations.AddField(
            model_name='assetlocationassetlistservicehistories',
            name='svc_hist_type_req_fl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='act_dpos_flg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='act_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='act_resrc_reqmt_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='act_type_cd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='actvn_dttm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='anniversary_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='asset_id_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='bo_status_cd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='break_in_dttm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='cost_center_cd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='crew_shift_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='descr100',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='descrlong',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='descrlong_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='emergency_flg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='held_for_parts_flg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='maint_sched_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='maint_trigger_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='node_id_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='participation_flg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='percentage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='percentage_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='planner_cd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='requestor_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='required_by_dt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='resrc_src_flg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='resrc_type_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='sched_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='seqno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='service_class_cd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='tmpl_act_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='total_priority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='total_priority_src_flg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='unit_price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='user_id_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='w1_descr100_upr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='w1_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='w1_quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='wo_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='work_priority_flg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='asset_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='asset_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
