# Generated by Django 2.2.6 on 2021-01-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_auto_20210121_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlocationassetlistservicehistories',
            name='question',
            field=models.ManyToManyField(blank=True, to='operations.ServiceHistoriesQuestions'),
        ),
        migrations.AlterField(
            model_name='servicehistoriesquestions',
            name='valid_value',
            field=models.ManyToManyField(blank=True, to='operations.QuestionsValidValue'),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletion',
            name='asset_location_asset_list',
            field=models.ManyToManyField(blank=True, to='operations.WorkOrderActivityCompletionAssetLocationAssetList'),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='service_histories',
            field=models.ManyToManyField(blank=True, to='operations.AssetLocationAssetListServiceHistories'),
        ),
    ]
