# Generated by Django 2.2.6 on 2021-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_auto_20210122_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalreading',
            name='reading_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='reading_datetime',
            field=models.DateTimeField(),
        ),
    ]
