# Generated by Django 2.2.6 on 2021-01-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_auto_20210126_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalreading',
            name='reading_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='reading_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
