# Generated by Django 2.2.6 on 2021-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_auto_20210126_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalreading',
            name='reading_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
