# Generated by Django 2.2.6 on 2021-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_auto_20210126_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocationassetlistservicehistories',
            name='downtime_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='owning_organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletion',
            name='descr100',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletion',
            name='descrlong',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletion',
            name='w1_descr100_upr',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
