# Generated by Django 2.2.6 on 2021-02-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_auto_20210205_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='field_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='field_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
