# Generated by Django 2.2.6 on 2021-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_auto_20210218_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlocationassetlistservicehistories',
            name='end_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assetlocationassetlistservicehistories',
            name='start_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='questionsvalidvalue',
            name='text_valid',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='servicehistoriesquestions',
            name='response_datetime',
            field=models.DateTimeField(),
        ),
    ]
