# Generated by Django 2.2.6 on 2021-02-20 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_auto_20210219_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costCenter', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('Bo', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_operation', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_manager', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planner', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_hist_type', models.CharField(blank=True, max_length=100)),
                ('service_hist_desc', models.CharField(blank=True, max_length=100)),
                ('service_hist_bo', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('service_hist_subclass', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHistoryQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_seq', models.CharField(blank=True, max_length=100)),
                ('question_cd', models.CharField(blank=True, max_length=100)),
                ('question_desc', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHistoryQuestionValidValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_seq', models.CharField(blank=True, max_length=100)),
                ('answer_cd', models.CharField(blank=True, max_length=100)),
                ('answer_desc', models.CharField(blank=True, max_length=100)),
                ('point_value', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_function', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='workcategory',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='measurementtype',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='measurementtype',
            name='record_by',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='detail_description',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='record_by',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='bo_status',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='creation_date_time',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='down_time_start',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='record_by',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='record_date',
        ),
        migrations.AddField(
            model_name='workcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='work_category',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='approval_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='bo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='creation_datetime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='downtime_start',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='int10_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='work_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='work_request_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='asset_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='asset_id',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='node_id',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletion',
            name='asset_id_1',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletion',
            name='node_id_1',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='asset_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='node_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='asset_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='creation_user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='home_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='long_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='node_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='owning_access_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='planner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='requestor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='required_by_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='work_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='work_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='work_priority',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
