# Generated by Django 2.2.6 on 2021-02-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_auto_20210220_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistoryquestion',
            name='service_history_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_history_question_service_history_id', to='operations.ServiceHistory'),
        ),
        migrations.AddField(
            model_name='servicehistoryquestionvalidvalue',
            name='service_history_question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_history_question_valid_value_service_history_id', to='operations.ServiceHistory'),
        ),
        migrations.AddField(
            model_name='servicehistoryquestionvalidvalue',
            name='style',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
