# Generated by Django 2.2.6 on 2021-02-21 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('operations', '0028_auto_20210221_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkActivityEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_work_activity_employee_id', to='employee.Employee')),
                ('work_order_activity_completion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_activity_emplyee_work_order_activity_completion_id', to='operations.WorkOrderActivityCompletion')),
            ],
        ),
    ]
