# Generated by Django 2.2.6 on 2021-02-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_workactivityemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistoryquestionvalidvalue',
            name='service_history_question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_history_question_valid_value_service_history_id', to='operations.ServiceHistoryQuestion'),
        ),
    ]
