# Generated by Django 2.2.6 on 2021-02-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_auto_20210221_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlocationassetlistservicehistories',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assetlocationassetlistservicehistories',
            name='start_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
