# Generated by Django 2.2.6 on 2021-03-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_auto_20210221_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderactivitycompletion',
            name='submitted_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
