# Generated by Django 2.2.6 on 2021-04-21 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_auto_20210304_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderActivityCompletionAssetLocationAssetListInbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(blank=True, max_length=12)),
                ('activityid', models.CharField(blank=True, max_length=100)),
                ('asset_id', models.CharField(blank=True, max_length=12)),
                ('participation', models.CharField(blank=True, max_length=100)),
                ('measurent_type', models.CharField(blank=True, max_length=100)),
                ('reading_type', models.CharField(blank=True, max_length=100)),
                ('current_value', models.CharField(blank=True, max_length=100)),
                ('asset_description', models.CharField(blank=True, max_length=100)),
                ('asset_type', models.CharField(blank=True, max_length=100)),
                ('reading_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('service_histories', models.ManyToManyField(blank=True, to='operations.AssetLocationAssetListServiceHistories')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLocationAssetListServiceHistoriesInbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activityid', models.CharField(blank=True, max_length=100)),
                ('service_history_type', models.CharField(blank=True, max_length=100)),
                ('effective_datetime', models.DateTimeField(auto_now=True)),
                ('start_date_time', models.DateTimeField(null=True)),
                ('end_date_time', models.DateTimeField(null=True)),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('failure_type', models.CharField(blank=True, max_length=100)),
                ('failure_mode', models.CharField(blank=True, max_length=100)),
                ('failure_repair', models.CharField(blank=True, max_length=100)),
                ('failure_component', models.CharField(blank=True, max_length=100)),
                ('failure_root_cause', models.CharField(blank=True, max_length=100)),
                ('svc_hist_type_req_fl', models.CharField(blank=True, max_length=100)),
                ('downtime_reason', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('question', models.ManyToManyField(blank=True, to='operations.ServiceHistoriesQuestions')),
            ],
        ),
    ]
