# Generated by Django 2.2.6 on 2021-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_assetlocationassetlistservicehistoriesinbound_workorderactivitycompletionassetlocationassetlistinbou'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocationassetlistservicehistoriesinbound',
            name='asset_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
