# Generated by Django 2.2.6 on 2021-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_assetlocationassetlistservicehistoriesinbound_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistoryquestionvalidvalue',
            name='answer_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
