# Generated by Django 2.2.6 on 2021-06-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_servicehistoryquestionvalidvalue_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='service_hist_desc',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='servicehistoryquestion',
            name='question_cd',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='servicehistoryquestion',
            name='question_desc',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='servicehistoryquestionvalidvalue',
            name='answer_cd',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='servicehistoryquestionvalidvalue',
            name='answer_desc',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='servicehistoryquestionvalidvalue',
            name='answer_text',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
