# Generated by Django 2.2.6 on 2021-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0036_auto_20210602_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistoriesquestions',
            name='response_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
