# Generated by Django 2.2.6 on 2021-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0038_workcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrequeststatus',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='workrequeststatus',
            name='record_by',
        ),
        migrations.AlterField(
            model_name='workrequeststatus',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workrequeststatus',
            name='work_request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
