# Generated by Django 2.2.6 on 2021-06-23 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0039_auto_20210613_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workorderactivitycompletion_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='record_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workorderactivitycompletion_record_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
