# Generated by Django 2.2.6 on 2021-06-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0040_auto_20210623_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalreading',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_operationalreading_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalreading',
            name='record_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_operationalreading_record_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequest_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='record_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_workrequest_record_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
