# Generated by Django 2.2.6 on 2021-06-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0041_auto_20210624_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderactivitycompletion',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='workorderactivitycompletion',
            name='record_by',
        ),
    ]
