apiVersion: apps/v1
kind: Deployment
metadata:
  name: airsel-rfid-api-deployment
  labels:
    app: airsel-rfid-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airsel-rfid-api
  template:
    metadata:
      labels:
        app: airsel-rfid-api
    spec:
      containers:
      - name: airsel-rfid-api
        # image: afeezaziz/rfid:1.3
        # image: syafiqpipe/airsel-rfid-api:1.0.71 #boleh tambah version
        image: yusliadi/airsel-rfid-api:1.0.72 #boleh tambah version
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: airsel-rfid-api-secret
