# Generated by Django 2.2.6 on 2020-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200705_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('AM', 'Asset Management System'), ('IV', 'Inventory'), ('OP', 'Operator'), ('SK', 'Store Keeper'), ('SS', 'Store Supervisor'), ('TC', 'Technical Crew'), ('VD', 'Vendor')], default='TC', max_length=2),
        ),
    ]
