# Generated by Django 2.2.6 on 2020-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200714_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name']},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nric',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Malaysia', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ic_number',
            field=models.CharField(blank=True, default='NA', max_length=14),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='NA', max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
