# Generated by Django 2.2.6 on 2021-06-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210325_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('AM', 'Admin'), ('OP', 'Operator'), ('TC', 'Technical Crew'), ('CR', 'Contractor'), ('PL', 'Planner')], default='TC', max_length=2),
        ),
    ]
