# Generated by Django 2.2.10 on 2021-06-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210608_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_access',
            field=models.BooleanField(default=True),
        ),
    ]
