# Generated by Django 2.2.6 on 2021-02-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failureprofile',
            name='failure_comp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='failureprofile',
            name='failure_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='failureprofile',
            name='failure_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
