# Generated by Django 2.2.6 on 2021-05-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_contactinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_information_employee_id', to='employee.Employee'),
        ),
    ]
