# Generated by Django 2.2 on 2021-08-04 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='NA', max_length=100)),
                ('inprogress', models.CharField(default='NA', max_length=100)),
                ('backLog', models.CharField(default='NA', max_length=100)),
                ('new', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ACS2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('noasset', models.CharField(default='NA', max_length=100)),
                ('one', models.CharField(default='NA', max_length=100)),
                ('two', models.CharField(default='NA', max_length=100)),
                ('three', models.CharField(default='NA', max_length=100)),
                ('four', models.CharField(default='NA', max_length=100)),
                ('five', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TAR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('total', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='NA', max_length=100)),
                ('inprogress', models.CharField(default='NA', max_length=100)),
                ('backLog', models.CharField(default='NA', max_length=100)),
                ('new', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
