# Generated by Django 2.2 on 2021-08-05 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210805_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owning_access_group', models.CharField(default='NA', max_length=100)),
                ('type', models.CharField(default='NA', max_length=100)),
                ('total', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
