# Generated by Django 2.2.6 on 2020-10-08 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'SS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_region', to='locations.Region'),
        ),
    ]
