# Generated by Django 2.2.6 on 2021-02-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210204_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaterial',
            name='source_locator',
            field=models.CharField(default='', max_length=100),
        ),
    ]
