# Generated by Django 2.2.6 on 2021-02-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210204_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygrn',
            name='auto_transact_code',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='bill_of_lading',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='business_unit',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='carrier_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='document_distribution_number',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='document_line_number',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='document_schedule_number',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='interface_line_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='interface_source_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='item_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='locator',
            field=models.CharField(blank=True, default='', max_length=81),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='organization_code',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='packing_slip',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='po_line_uom',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='receipt_source_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='source_document_code',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='sub_inventory_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='supplier_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='supplier_site_code',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventorygrn',
            name='way_bill',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_item',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_org_code',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_category',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='legal_entity_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='legal_entity_me',
            field=models.CharField(blank=True, default='', max_length=960),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='long_description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='primary_uom',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='purchasable_item',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='secondary_uom',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='shippable_item',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='transfer_orders_enbled',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='inventoryitemuominter',
            name='attribure1',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventoryitemuominter',
            name='conversion_rate',
            field=models.CharField(blank=True, default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='inventoryitemuominter',
            name='from_base_uom_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitemuominter',
            name='from_uom_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitemuominter',
            name='item_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventoryitemuominter',
            name='to_base_uom_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitemuominter',
            name='to_uom_class',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='inventoryitemuomintra',
            name='attribute1',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventoryitemuomintra',
            name='base_uom_rate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitemuomintra',
            name='conversion_rate',
            field=models.CharField(blank=True, default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='inventoryitemuomintra',
            name='from_uom_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitemuomintra',
            name='item_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventoryitemuomintra',
            name='uom_class',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='destination_account',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='destination_locator',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='destination_sub_inventory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='movement_request_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='source_locator',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='source_sub_inventory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='uom_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='address_line_3',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='address_name',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='base_uom_code',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='change_order_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='change_order_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='contact_email_address',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='contact_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='contact_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='contact_mobile_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='contact_phone_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='country',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='description',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='item_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='line_description',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='line_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='line_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='procurement_bu',
            field=models.CharField(blank=True, default='', max_length=960),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='ship_to_location',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='ship_to_organization',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='sold_to_legal_entity',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='state',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='sub_inventory_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='supplier_contact',
            field=models.CharField(blank=True, default='', max_length=360),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='supplier_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='supplier_site_code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='uom_code',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='COST_COMPONENT_CODE',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='ITEM_NUMBER',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='ORGANIZATION_CODE',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='SOURCE_CODE',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='SUBINVENTORY_CODE',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='TRANSACTION_COST_IDENTIFIER',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='TRANSACTION_REFERENCE',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='TRANSACTION_TYPE_NAME',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='TRANSACTION_UOM',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
