# Generated by Django 2.2.6 on 2020-07-05 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='created_date',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='organisation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='shortname',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
