# Generated by Django 2.2.6 on 2020-12-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='shortname',
        ),
    ]
