# Generated by Django 2.2.6 on 2020-07-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200705_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
